import { NextResponse } from "next/server";
import { jsPDF } from "jspdf";
import type { Character, Location, TimelineEvent, WorldRule } from "@/types";
import { createServerSupabase } from "@/lib/supabase-server";

export const dynamic = "force-dynamic";

export async function POST(req: Request) {
  try {
    const supabase = createServerSupabase();
    const { data: { session } } = await supabase.auth.getSession();

    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { series_id } = await req.json();
    if (!series_id) {
      return NextResponse.json({ error: "series_id required" }, { status: 400 });
    }

    const { data: series } = await supabase
      .from("tk_series")
      .select("*")
      .eq("id", series_id)
      .eq("user_id", session.user.id)
      .single();

    if (!series) {
      return NextResponse.json({ error: "Series not found" }, { status: 404 });
    }

    const [charsRes, locsRes, eventsRes, rulesRes] = await Promise.all([
      supabase.from("tk_characters").select("*").eq("series_id", series_id).order("name"),
      supabase.from("tk_locations").select("*").eq("series_id", series_id).order("name"),
      supabase.from("tk_timeline_events").select("*").eq("series_id", series_id).order("event_order"),
      supabase.from("tk_world_rules").select("*").eq("series_id", series_id).order("category"),
    ]);

    const characters: Character[] = charsRes.data || [];
    const locations: Location[] = locsRes.data || [];
    const events: TimelineEvent[] = eventsRes.data || [];
    const rules: WorldRule[] = rulesRes.data || [];

    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    const pageW = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentW = pageW - margin * 2;
    let y = margin;

    const checkPageBreak = (needed = 20) => {
      if (y + needed > doc.internal.pageSize.getHeight() - margin) {
        doc.addPage();
        y = margin;
      }
    };

    const addHeading = (text: string, size = 18, color: [number, number, number] = [30, 58, 95]) => {
      checkPageBreak(size + 8);
      doc.setFontSize(size);
      doc.setTextColor(...color);
      doc.setFont("helvetica", "bold");
      doc.text(text, margin, y);
      y += size * 0.5 + 4;
    };

    const addSubHeading = (text: string) => {
      checkPageBreak(14);
      doc.setFontSize(13);
      doc.setTextColor(30, 58, 95);
      doc.setFont("helvetica", "bold");
      doc.text(text, margin, y);
      y += 8;
    };

    const addBody = (text: string, indent = 0) => {
      if (!text) return;
      doc.setFontSize(10);
      doc.setTextColor(60, 80, 100);
      doc.setFont("helvetica", "normal");
      const lines = doc.splitTextToSize(text, contentW - indent);
      checkPageBreak(lines.length * 5 + 4);
      doc.text(lines, margin + indent, y);
      y += lines.length * 5 + 3;
    };

    const addLabel = (label: string, value: string) => {
      if (!value) return;
      doc.setFontSize(9);
      doc.setTextColor(100, 120, 140);
      doc.setFont("helvetica", "bold");
      doc.text(label.toUpperCase() + ":", margin + 4, y);
      y += 5;
      addBody(value, 4);
    };

    const addDivider = () => {
      checkPageBreak(6);
      doc.setDrawColor(220, 215, 205);
      doc.line(margin, y, margin + contentW, y);
      y += 5;
    };

    // Cover page
    doc.setFillColor(30, 58, 95);
    doc.rect(0, 0, pageW, doc.internal.pageSize.getHeight(), "F");
    doc.setFontSize(32);
    doc.setTextColor(255, 253, 251);
    doc.setFont("helvetica", "bold");
    doc.text(series.name, pageW / 2, 90, { align: "center" });
    doc.setFontSize(16);
    doc.setTextColor(180, 83, 9);
    doc.text("Series Bible", pageW / 2, 104, { align: "center" });
    doc.setFontSize(10);
    doc.setTextColor(150, 170, 200);
    doc.text(`Generated by ThreadKey · ${new Date().toLocaleDateString()}`, pageW / 2, 115, { align: "center" });

    // Characters section
    doc.addPage();
    y = margin;
    addHeading("CHARACTERS", 22);
    doc.setFillColor(220, 215, 205);
    doc.rect(margin, y, contentW, 0.5, "F");
    y += 8;

    for (const char of characters) {
      checkPageBreak(30);
      addSubHeading(char.name);
      if (char.first_appearance) addLabel("First Appearance", char.first_appearance);
      if (char.physical_description?.length > 0) addLabel("Physical Description", char.physical_description.join(". "));
      if (char.personality_traits?.length > 0) addLabel("Personality", char.personality_traits.join(", "));
      if (char.relationships?.length > 0) {
        const relText = char.relationships
          .map((r: { character?: string; relationship?: string } | string) =>
            typeof r === "string" ? r : `${r.character || ""} (${r.relationship || ""})`
          )
          .join("; ");
        addLabel("Relationships", relText);
      }
      if (char.key_events?.length > 0) addLabel("Key Events", char.key_events.join(". "));
      if (char.source_refs?.length > 0) {
        const refs = char.source_refs.map((r: { book_number: number; chapter_number: number }) => `Book ${r.book_number}, Ch. ${r.chapter_number}`).join("; ");
        doc.setFontSize(8);
        doc.setTextColor(180, 83, 9);
        doc.text("Sources: " + refs, margin + 4, y);
        y += 5;
      }
      addDivider();
    }

    // Locations
    doc.addPage();
    y = margin;
    addHeading("LOCATIONS", 22);
    doc.setFillColor(220, 215, 205);
    doc.rect(margin, y, contentW, 0.5, "F");
    y += 8;

    for (const loc of locations) {
      checkPageBreak(25);
      addSubHeading(loc.name);
      if (loc.description) addLabel("Description", loc.description);
      if (loc.significance) addLabel("Significance", loc.significance);
      addDivider();
    }

    // Timeline
    doc.addPage();
    y = margin;
    addHeading("TIMELINE", 22);
    doc.setFillColor(220, 215, 205);
    doc.rect(margin, y, contentW, 0.5, "F");
    y += 8;

    events.forEach((ev, idx) => {
      checkPageBreak(25);
      addSubHeading(`${idx + 1}. ${ev.event}`);
      if (ev.when_occurred) addLabel("When", ev.when_occurred);
      if (ev.who_involved?.length > 0) addLabel("Who", Array.isArray(ev.who_involved) ? ev.who_involved.join(", ") : String(ev.who_involved));
      if (ev.consequences) addLabel("Consequences", ev.consequences);
      addDivider();
    });

    // World Rules
    doc.addPage();
    y = margin;
    addHeading("WORLD RULES", 22);
    doc.setFillColor(220, 215, 205);
    doc.rect(margin, y, contentW, 0.5, "F");
    y += 8;

    const rulesByCategory = rules.reduce<Record<string, WorldRule[]>>((acc, rule) => {
      const cat = rule.category || "General";
      if (!acc[cat]) acc[cat] = [];
      acc[cat].push(rule);
      return acc;
    }, {});

    for (const [category, catRules] of Object.entries(rulesByCategory)) {
      checkPageBreak(20);
      addHeading(category, 14, [180, 83, 9]);
      for (const rule of catRules) {
        addBody("• " + rule.rule_description, 4);
        if (rule.details) addBody(rule.details, 8);
        y += 2;
      }
      y += 4;
    }

    const pdfBuffer = Buffer.from(doc.output("arraybuffer"));

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${series.name.replace(/[^a-z0-9]/gi, "_")}_series_bible.pdf"`,
        "Content-Length": String(pdfBuffer.length),
      },
    });
  } catch (err: unknown) {
    console.error("Export error:", err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Export failed" },
      { status: 500 }
    );
  }
}
